# Site
name: "Go Woke Go Broke"
title: "Go Woke Go Broke"
description: "When businesses lose touch with their core customer base, their financial stability is put at risk. Stand up for your values, boycott woke corporations."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
google_analytics: ''
disqus: 'gobroke'
mailchimp-list: 'https://gobroke.us17.list-manage.com/subscribe/post?u=b62af801b1c07decba83359e5&amp;id=7ed38369fd&amp;f_id=00127de0f0'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Tyler Durden
    display_name: Tyler Durden
    gravatar: 5f4e6aace9a7c3d20eb58f631ea63b25
    email: gobrokecontact@protonmail.com
    web: https://gobroke.org
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
